import Foundation

enum MarkdownExporter {
    /// Export as Markdown with timestamps
    static func export(
        title: String,
        segments: [TranscriptionSegment],
        includeTimecodes: Bool = true,
        includeTranslation: Bool = false,
        meetingSummary: String? = nil
    ) -> String {
        var lines: [String] = []

        lines.append("# \(title)")
        lines.append("")
        lines.append("*Generated by MemoVoice*")
        lines.append("")

        // Summary section
        if let summary = meetingSummary {
            lines.append("## Summary")
            lines.append("")
            lines.append(summary)
            lines.append("")
        }

        // Transcript section
        lines.append("## Transcript")
        lines.append("")

        for segment in segments {
            if includeTimecodes {
                lines.append("**[\(segment.displayStartTime)]** \(segment.text)")
            } else {
                lines.append(segment.text)
            }

            if includeTranslation, let translated = segment.translatedText {
                lines.append("")
                lines.append("> \(translated)")
            }

            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    /// Write Markdown file
    static func write(
        title: String,
        segments: [TranscriptionSegment],
        to url: URL,
        includeTimecodes: Bool = true,
        includeTranslation: Bool = false,
        meetingSummary: String? = nil
    ) throws {
        let content = export(
            title: title,
            segments: segments,
            includeTimecodes: includeTimecodes,
            includeTranslation: includeTranslation,
            meetingSummary: meetingSummary
        )
        try content.write(to: url, atomically: true, encoding: .utf8)
    }
}
